# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7b6f0fc6baa65278d4004734affdb5c4babb0a81b4ee96c08a68705b6f6807e565b99622e6b27574367e7d650bbd4f70624741054ec1776a03dd914fe972bf6

test:
  secret_key_base: a1fe93bcbf2ad6535deeb35a83248610db241f1584fa4b2ee5ac2fadef881903be2579d9d6775c1c2a958fcdc78cccd336e00c8f852f1a94ac897333b62e44b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
